# Generated by Django 3.0.8 on 2020-07-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200703_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_active',
            field=models.NullBooleanField(default=True),
        ),
    ]
